/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package forms;

import controller.Controller;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import util.Mesto;
import util.NarucilacUsluge;
import util.Otpremnica;
import util.Vozac;

/**
 *
 * @author Marko
 */
public class CreateOtpremnicaForm extends javax.swing.JDialog {

    List<JTextField> textFields = new ArrayList<>();
    private Locale currentLocale;
    private ResourceBundle messages;

    /**
     * Creates new form DetailsOtpremnicaForm
     */
    public CreateOtpremnicaForm(java.awt.Frame parent, boolean modal, Locale currentLocale) throws IOException {
        super(parent, modal);
        initComponents();
        this.currentLocale = currentLocale;
        switch (currentLocale.getLanguage()) {
            case "sr" ->
                lblDateOtpremnica.setText("Današnji datum : " + Controller.getInstance().convertDate(new Date()));
            case "sr_cir" ->
                lblDateOtpremnica.setText("Данашњи датум : " + Controller.getInstance().convertDate(new Date()));
            default ->
                lblDateOtpremnica.setText("Today's date : " + Controller.getInstance().convertDate(new Date()));
        }
        loadLanguage();
        updateTexts();
        addListeners();
        fillcombo();
        txtMailV.setEditable(false);
        txtPhoneV.setEditable(false);
        txtDriverType.setEditable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNU = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        txtLastNameNU = new javax.swing.JTextField();
        lblAdress = new javax.swing.JLabel();
        txtAdressNU = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhoneNU = new javax.swing.JTextField();
        lblMail = new javax.swing.JLabel();
        txtMailNU = new javax.swing.JTextField();
        lblPlace = new javax.swing.JLabel();
        txtMailV = new javax.swing.JTextField();
        lblVehicleType = new javax.swing.JLabel();
        lblDriver = new javax.swing.JLabel();
        txtDriverType = new javax.swing.JTextField();
        lblNameLastName = new javax.swing.JLabel();
        lblPhone2 = new javax.swing.JLabel();
        txtPhoneV = new javax.swing.JTextField();
        lblMail2 = new javax.swing.JLabel();
        lblDateOtpremnica = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        comboVozac = new javax.swing.JComboBox<>();
        comboMesto = new javax.swing.JComboBox<>();
        txtNameNU = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        lblErrorName = new javax.swing.JLabel();
        lblErrorLastName = new javax.swing.JLabel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorMail = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        lblFind = new javax.swing.JLabel();
        btnFind = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNU.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNU.setText("Naručilac usluge");

        lblTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblTitle.setText("Kreiraj Otpremnicu");

        lblName.setText("Ime");

        lblAdress.setText("Adresa");

        lblPhone.setText("Telefon");

        lblMail.setText("Email");

        lblPlace.setText("Mesto i poštanski broj");

        lblVehicleType.setText("Vrsta prevoznog sredstva");

        lblDriver.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDriver.setText("Vozač");

        lblNameLastName.setText("Ime i Prezime");

        lblPhone2.setText("Telefon");

        lblMail2.setText("Email");

        lblDateOtpremnica.setText("datum");

        btnSave.setText("Sacuvaj");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        comboVozac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboVozacActionPerformed(evt);
            }
        });

        lblLastName.setText("Prezime");

        lblErrorName.setForeground(new java.awt.Color(255, 0, 0));

        lblErrorLastName.setForeground(new java.awt.Color(255, 0, 51));

        lblErrorPhone.setForeground(new java.awt.Color(255, 51, 51));

        lblErrorMail.setForeground(new java.awt.Color(255, 51, 51));

        lblFind.setText("Pretrazi");

        btnFind.setText("jButton1");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblDateOtpremnica, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNU)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(77, 77, 77)
                                        .addComponent(lblFind))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(96, 96, 96)
                                            .addComponent(lblName))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAdress, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPhone, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblPlace, javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(lblMail, javax.swing.GroupLayout.Alignment.TRAILING))
                                        .addComponent(lblLastName, javax.swing.GroupLayout.Alignment.TRAILING)))
                                .addGap(59, 59, 59)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtLastNameNU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtAdressNU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtNameNU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtPhoneNU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMailNU, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrorMail, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrorPhone, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnSave, javax.swing.GroupLayout.Alignment.TRAILING)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(31, 31, 31)
                                        .addComponent(btnFind)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblErrorLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(lblDriver))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblPhone2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtPhoneV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblMail2)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtMailV, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblNameLastName)
                                    .addGap(18, 18, 18)
                                    .addComponent(comboVozac, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblVehicleType)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDriverType, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(127, 127, 127))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitle)
                    .addComponent(lblDateOtpremnica))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDriver)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNameLastName)
                            .addComponent(comboVozac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPhone2)
                            .addComponent(txtPhoneV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtMailV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblMail2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblVehicleType)
                            .addComponent(txtDriverType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblErrorPhone))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNU)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblErrorName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblErrorLastName)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFind)
                                    .addComponent(txtFind, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFind))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblName)
                                        .addGap(12, 12, 12)
                                        .addComponent(lblLastName)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblAdress)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblPhone)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblMail)
                                        .addGap(15, 15, 15)
                                        .addComponent(lblPlace))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtNameNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtLastNameNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtAdressNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPhoneNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMailNU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(comboMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addComponent(lblErrorMail)
                .addGap(36, 36, 36)
                .addComponent(btnSave)
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        Vozac selectedVozac = (Vozac) comboVozac.getSelectedItem();
        Mesto selectedMesto = (Mesto) comboMesto.getSelectedItem();

        String name = txtNameNU.getText();
        String lastName = txtLastNameNU.getText();
        String phone = txtPhoneNU.getText();
        String mail = txtMailNU.getText();
        String adress = txtAdressNU.getText();

        if (lblErrorName.getText().equals("")
                && lblErrorLastName.getText().equals("")
                && lblErrorMail.getText().equals("")
                && lblErrorPhone.getText().equals("")
                && !txtNameNU.getText().isEmpty()
                && !txtLastNameNU.getText().isEmpty()
                && !txtPhoneNU.getText().isEmpty()
                && !txtMailNU.getText().isEmpty()
                && !txtAdressNU.getText().isEmpty()) {
            NarucilacUsluge param2 = new NarucilacUsluge(-1, name, lastName, adress, phone, mail, selectedMesto);
            int id = 0;
            try {
                id = Controller.getInstance().insertNarucilacUsluge(param2);
            } catch (IOException ex) {
                Logger.getLogger(CreateOtpremnicaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            Date danas = new Date();
            Calendar c = Calendar.getInstance();
            c.setTime(danas);
            int d = c.get(Calendar.DAY_OF_MONTH);
            int m = c.get(Calendar.MONTH) + 1;
            int y = c.get(Calendar.YEAR);
            String dan = y + "-" + m + "-" + d;
            NarucilacUsluge nu = new NarucilacUsluge(id, name, lastName, adress, phone, mail, selectedMesto);
            Otpremnica param = new Otpremnica(-1, danas, selectedVozac, nu);
            int idOtpremnica = 0;
            try {
                idOtpremnica = Controller.getInstance().insertOtpremnica(param);
            } catch (IOException ex) {
                Logger.getLogger(CreateOtpremnicaForm.class.getName()).log(Level.SEVERE, null, ex);
            }
            Otpremnica o = new Otpremnica(idOtpremnica, danas, selectedVozac, nu);
            if (idOtpremnica != -1) {
                try {
                    switch (currentLocale.getLanguage()) {
                        case "sr" ->
                            JOptionPane.showMessageDialog(this, "Uspešno sačuvane promene");
                        case "sr_cir" ->
                            JOptionPane.showMessageDialog(this, "Успешно сачуване промене");
                        default ->
                            JOptionPane.showMessageDialog(this, "Changes saved successfully");
                    }
                    UpdateOtpremnicaForm otpremnicaForm = new UpdateOtpremnicaForm(null, true, o, currentLocale);
                    otpremnicaForm.setLocationRelativeTo(null);
                    otpremnicaForm.setVisible(true);
                    this.dispose();
                } catch (IOException ex) {
                    Logger.getLogger(CreateOtpremnicaForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else {
            switch (currentLocale.getLanguage()) {
                case "sr" ->
                    JOptionPane.showMessageDialog(this, "Greška, nisu uneti pravilno svi podaci", "Greška", JOptionPane.ERROR_MESSAGE);
                case "sr_cir" ->
                    JOptionPane.showMessageDialog(this, "Грешка, нису унети правилно сви подаци", "Грешка", JOptionPane.ERROR_MESSAGE);
                default ->
                    JOptionPane.showMessageDialog(this, "Error, not all data was entered correctly", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void comboVozacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboVozacActionPerformed
        Vozac selected = (Vozac) comboVozac.getSelectedItem();
        txtMailV.setText(selected.getEmail());
        List<String> vehicles = null;
        try {
            vehicles = Controller.getInstance().getVehicles(selected.getIdVozac());
        } catch (IOException ex) {
            Logger.getLogger(CreateOtpremnicaForm.class.getName()).log(Level.SEVERE, null, ex);
        }
        String v = "";
        for (String vehicle : vehicles) {
            v = v + " " + vehicle;
        }
        txtDriverType.setText(v);
        txtPhoneV.setText(selected.getPhoneNumber());
    }//GEN-LAST:event_comboVozacActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        try {
            String search = txtFind.getText().trim();
            HashMap<Integer, String> map = new HashMap<>();
            map.put(7, search);
            List<NarucilacUsluge> list = Controller.getInstance().getListNarucilacUsluge(map);
            if (list.isEmpty()) {
                switch (currentLocale.getLanguage()) {
                    case "sr" ->
                        JOptionPane.showMessageDialog(this, "Nije pronađen nijedan korisnik", "Greška", JOptionPane.ERROR_MESSAGE);
                    case "sr_cir" ->
                        JOptionPane.showMessageDialog(this, "Није пронађен ниједан корисник", "Грешка!", JOptionPane.ERROR_MESSAGE);
                    default ->
                        JOptionPane.showMessageDialog(this, "No users found", "Error!", JOptionPane.ERROR_MESSAGE);
                }
            } else {
                int k = switch (currentLocale.getLanguage()) {
                    case "sr" ->
                        JOptionPane.showConfirmDialog(rootPane, "Da li ste mislili na mejl adresu? \n" + list.get(0).getEmail());
                    case "sr_cir" ->
                        JOptionPane.showConfirmDialog(rootPane, "Да ли сте мислили на мејл адресу? \n" + list.get(0).getEmail());
                    default ->
                        JOptionPane.showConfirmDialog(rootPane, "Did you mean this email address? \n" + list.get(0).getEmail());
                };

                System.out.println(k);
                switch (k) {
                    case JOptionPane.YES_OPTION:
                        txtNameNU.setText(list.get(0).getName());
                        txtLastNameNU.setText(list.get(0).getLastName());
                        txtPhoneNU.setText(list.get(0).getPhone());
                        txtMailNU.setText(list.get(0).getEmail());
                        txtAdressNU.setText(list.get(0).getAdress());

//                        txtAdressNU.setEditable(false);
//                        txtMailNU.setEditable(false);
//                        txtPhoneNU.setEditable(false);
//                        txtLastNameNU.setEditable(false);
//                        txtNameNU.setEditable(false);
                        break;
                    default:

                }
            }
        } catch (IOException ex) {
            Logger.getLogger(DetailsNarucilacUslugeForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFindActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Mesto> comboMesto;
    private javax.swing.JComboBox<Vozac> comboVozac;
    private javax.swing.JLabel lblAdress;
    private javax.swing.JLabel lblDateOtpremnica;
    private javax.swing.JLabel lblDriver;
    private javax.swing.JLabel lblErrorLastName;
    private javax.swing.JLabel lblErrorMail;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblFind;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMail2;
    private javax.swing.JLabel lblNU;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblNameLastName;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhone2;
    private javax.swing.JLabel lblPlace;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblVehicleType;
    private javax.swing.JTextField txtAdressNU;
    private javax.swing.JTextField txtDriverType;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtLastNameNU;
    private javax.swing.JTextField txtMailNU;
    private javax.swing.JTextField txtMailV;
    private javax.swing.JTextField txtNameNU;
    private javax.swing.JTextField txtPhoneNU;
    private javax.swing.JTextField txtPhoneV;
    // End of variables declaration//GEN-END:variables

    private void fillcombo() throws IOException {
        List<Vozac> list = Controller.getInstance().getListVozac();
        for (Vozac vozac : list) {
            comboVozac.addItem(vozac);
        }

        List<Mesto> lista = Controller.getInstance().getListMesto();
        for (Mesto mesto : lista) {
            comboMesto.addItem(mesto);
        }

    }

    private void checkFields() {
        boolean allFilled = Controller.validateTextFields(textFields);
        btnSave.setEnabled(allFilled);
    }

    private void addListeners() throws IOException {

        textFields.add(txtLastNameNU);
        textFields.add(txtNameNU);
        textFields.add(txtMailNU);
        textFields.add(txtPhoneNU);
        textFields.add(txtAdressNU);

        for (JTextField textField : textFields) {
            textField.getDocument().addDocumentListener(new DocumentListener() {
                @Override
                public void insertUpdate(DocumentEvent e) {
                    checkFields();
                }

                @Override
                public void removeUpdate(DocumentEvent e) {
                    checkFields();
                }

                @Override
                public void changedUpdate(DocumentEvent e) {
                    checkFields();
                }
            });
        }
        Controller.getInstance().checkPhone(txtPhoneNU, lblErrorPhone, currentLocale);
        Controller.getInstance().checkMail(txtMailNU, lblErrorMail, currentLocale);
        switch (currentLocale.getLanguage()) {
            case "sr":
                Controller.getInstance().checkName(txtNameNU, lblErrorName, "Loš unos imena.");
                Controller.getInstance().checkName(txtLastNameNU, lblErrorLastName, "Loš unos prezimena.");
                break;
            case "sr_cir":
                Controller.getInstance().checkName(txtNameNU, lblErrorName, "Лош унос имена.");
                Controller.getInstance().checkName(txtLastNameNU, lblErrorLastName, "Лош унос презимена.");
                break;
            default:
                Controller.getInstance().checkName(txtNameNU, lblErrorName, "Bad name input.");
                Controller.getInstance().checkName(txtLastNameNU, lblErrorLastName, "Bad lastname input.");
                break;

        }

    }

    public void loadLanguage() {
        try {
            messages = ResourceBundle.getBundle("translate.messages", currentLocale);
        } catch (Exception e) {
            System.err.println("Greška pri učitavanju jezika: " + e.getMessage());
        }
    }

    public void updateTexts() {
        lblLastName.setText(messages.getString("lblLastName.text"));
        lblMail.setText(messages.getString("lblMail.text"));
        lblName.setText(messages.getString("lblName.text"));
        lblPhone.setText(messages.getString("lblPhone.text"));
        lblAdress.setText(messages.getString("lblAdress.text"));
        lblPlace.setText(messages.getString("lblPlace.text"));
        lblVehicleType.setText(messages.getString("lblVehicleType.text"));
        lblPhone2.setText(messages.getString("lblPhone2.text"));
        lblMail2.setText(messages.getString("lblMail2.text"));
        btnSave.setText(messages.getString("btnSave.text"));
        lblNameLastName.setText(messages.getString("lblNameLastNameF.text"));
        lblNU.setText(messages.getString("lblNU.text"));
        lblDriver.setText(messages.getString("lblDriver.text"));
        lblTitle.setText(messages.getString("lblTitle.text"));
        btnFind.setText(messages.getString("btnFind.text"));
        lblFind.setText(messages.getString("btnFind.text"));
    }
}
